version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    schedule:
      interval: 'monthly'
    groups:
      types:
        patterns:
        - '@types/*'      

  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    rebase-strategy: disabled
    schedule:
      interval: "monthly"
    groups:
      all:
        patterns:
        - '*'
